export enum PD2Website {
    Api = 'https://api.projectdiablo2.com',
    Website = 'https://projectdiablo2.com'
}

// Rune hierarchy order (highest to lowest)
export const RUNE_HIERARCHY = [
  'Zod Rune',
  'Cham Rune',
  'Jah Rune',
  'Ber Rune',
  'Sur Rune',
  'Lo Rune',
  'Ohm Rune',
  'Vex Rune',
  'Gul Rune',
  'Ist Rune',
  'Mal Rune',
  'Um Rune',
  'Pul Rune',
  'Lem Rune',
  'Fal Rune',
  'Ko Rune',
  'Lum Rune',
  'Io Rune',
  'Hel Rune',
  'Dol Rune',
  'Shael Rune',
  'Sol Rune',
  'Amn Rune',
  'Thul Rune',
  'Ort Rune',
  'Ral Rune',
  'Tal Rune',
  'Ith Rune',
  'Eth Rune',
  'Nef Rune',
  'Tir Rune',
  'Eld Rune',
  'El Rune',
];